FROM python:latest

# Install packages.
RUN apt-get --yes update

# Install git
RUN apt-get --yes install git

# Install Vim
RUN apt-get --yes install vim

# Install Shells
RUN apt-get --yes install fish

# Install pick
RUN apt-get install -y pick

# Install cli trash command
RUN apt-get --yes install trash-cli

# Install zip
RUN apt-get --yes install zip unzip

# Install http cli clients
RUN apt-get --yes install curl wget httpie

# Install ag
RUN apt-get --yes install silversearcher-ag

# Install tmux
RUN apt-get --yes install tmux

# Install aws cli command
RUN apt-get --yes install awscli

# Install Python
# RUN apt-get --yes install python-pip python3-pip python3-dev python3-setuptools python3-wheel
